name: Windows (x64)

on:
  push:
      branches: 
        - "*"
      tags:
        - "*"
    
  pull_request:
      branches: 
        - "*"

jobs:
  build-projectm:
    name: Build ProjectM
    runs-on: windows-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'projectM-visualizer/projectm'
          submodules: 'recursive'

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Get ProjectM Git Hash
        id: git-hash
        run: echo "hash=$(git rev-parse HEAD)" >> $Env:GITHUB_OUTPUT

      - name: Cache Install
        id: cache-install
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/install
          key: install-${{ runner.os }}-projectm-${{ steps.git-hash.outputs.hash }}

      - name: Configure Build
        run: cmake -G "Visual Studio 17 2022" -A "X64" -S "${{ github.workspace }}" -B "${{ github.workspace }}/cmake-build" -DCMAKE_TOOLCHAIN_FILE="${Env:VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install" -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>DLL" -DCMAKE_VERBOSE_MAKEFILE=YES -DBUILD_SHARED_LIBS=ON
        if: steps.cache-install.outputs.cache-hit != 'true'

      - name: Build Release
        run: cmake --build "${{ github.workspace }}/cmake-build" --config "Release" --parallel
        if: steps.cache-install.outputs.cache-hit != 'true'

      - name: Install
        run: |
          cmake --build "${{ github.workspace }}/cmake-build" --config "Release" --target install
        if: steps.cache-install.outputs.cache-hit != 'true'
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: projectm-windows-shared-latest
            path: install/*

  build-plugin:
    name: Build GST Plugin ProjectM
    runs-on: windows-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Wait for ProjectM
        uses: yogeshlonkar/wait-for-jobs@v0
        with:
          interval: '5000'
          jobs: Build ProjectM
          ttl: '15'

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: projectm-windows-shared-latest
          path: artifacts

      - name: Configure Build
        run: cmake -G "Visual Studio 17 2022" -A "X64" -S "${{ github.workspace }}" -B "${{ github.workspace }}/cmake-build" -DCMAKE_TOOLCHAIN_FILE="${Env:VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>" -DCMAKE_VERBOSE_MAKEFILE=YES -DprojectM4_DIR="artifacts/lib/cmake/projectM4"

      - name: Build Release
        id: build
        run: cmake --build "${{ github.workspace }}/cmake-build" --config "Release" --parallel

      # - name: Install Chocolatey
      #   uses: crazy-max/ghaction-chocolatey@v3
      #   with:
      #     args: install gstreamer --no-progress
      #   if: steps.build.outputs.return-code == 0

      # - name: Test
      #   run: |
      #     set GST_PLUGIN_PATH="${{ github.workspace }}/cmake-build/Release"
      #     gst-inspect-1.0 projectm
      #   if: steps.build.outputs.return-code == 0

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: gst-projectm-windows-latest
            path: ${{ github.workspace }}\cmake-build\Release\*.dll